### ISSUE TITLE
Somehow, plugin is not working

### ISSUE THREAD

**Issue by RickCogley** [otaviocc/plugin-reply-on-mastodon#1]
Hello - I'm trying to use this plugin, with Tiny theme. I updated Tiny which now includes code to allow this plugin to work automatically, and was able to install this without error. The recent update of Tiny was just its single template, adding conditional code for this plugin. 

I examined the single template, to confirm that the code to load the plugin is there. However, none of my posts (crossposted to mastodon) are showing the link that this plugin is supposed to create. 

How can I troubleshoot this?

**Comment by otaviocc** [comment]
@RickCogley what happens if you go to Account > Logging and rebuild your blog? Does it start showing the button?

**Comment by otaviocc** [comment]
@RickCogley also, are you cross-posting to Mastodon or is your blog a Mastodon instance? The plugin is meant for people who cross-post their posts to a Mastodon account.

**Comment by RickCogley** [comment]
Hi @otaviocc thanks for the advice. I've tried the "rebuild" button a couple times but so far, no dice. I'm just cross posting to `@rickcogley@famichiki.jp`, a masto account. When you say "is your blog a mastodon instance" I'm not sure what you mean. It's micro.blog of course, but is there a setting that makes it a mastodon instance or something? If so please advise where I set that, and  I will check!

**Comment by otaviocc** [comment]
Hey @RickCogley, from what I can gather, you're posting on Micro.blog but not cross-posting to another Mastodon instance.

Your Micro.blog is set up to function as an instance (specifically, instance `cogley.jp`, under the user `@rick@cogley.jp`). Additionally, you maintain a separate Mastodon account, `@rickcogley@famichiki.jp`, hosted on the `famichiki.jp` instance.

It appears that you post on Micro.blog and then boost these posts using your `@rickcogley@famichiki.jp` account.

My suggestion is to configure Micro.blog to cross-post directly to `@rickcogley@famichiki.jp`, eliminating the need to boost your posts manually. You can configure this by visiting [your Micro.blog Account](https://micro.blog/account/feeds) settings.

**Comment by RickCogley** [comment]
@otaviocc ah, thanks for the sleuthing! You're totally right and I'm sorry to have wasted your time. I started doing that to try to see if I could stick to one account for masto, following people on masto from within the m.b. UI. I'll test.

**Comment by RickCogley** [comment]
Yep. Now I see that this works perfectly. So embarrassing!
