### ISSUE TITLE
Which micro.blog themes allready use this plugin?

### ISSUE THREAD

**Issue by Suitbert** [otaviocc/plugin-reply-on-mastodon#2]
Newbie and non-developer question: Which micro.blog themes allready use this plugin? Thanks for the info!
regards,
Suitbert

**Comment by otaviocc** [comment]
I've added the support to Tiny Theme (via a Pull Request), but I don't know which other themes are using it. I would suggest users to contact the developer of themes to include it and/or edit the theme via Micro.blog to add the support to the plugin. It should be straight-forward in most themes.
