### ISSUE TITLE
Font Awesome icons not working

### ISSUE THREAD

**Issue by umerez** [otaviocc/plugin-reply-on-mastodon#3]
Hi, I'm trying to add a Mastodon Font Awesome icon to the `Reply on Mastodon` button and it does not work. Other plug-ins like `Conversation on micro.blog` or `Reply by Email` show the icons properly but not in this case. Am I doing something wrong? I've tried with these two codes and none work:

`<i class="fa-brands fa-mastodon"></i>` 
`<i class="fa-brands fa-mastodon" style="color: #3988a7;"></i>` 

Any help would be appreciated. Thanks!

Esteban Umerez

**Comment by otaviocc** [comment]
Hi @umerez! I'll work on it this weekend!

**Comment by otaviocc** [comment]
Done :-)

<img width="595" alt="Screenshot 2024-01-21 at 00 46 45" src="https://github.com/otaviocc/plugin-reply-on-mastodon/assets/139272/ce059bbc-827a-4dd8-acb8-49fff02590a5">

Now it should work with Font Awesome.

**Comment by umerez** [comment]
Yes! Thank you so much.—Esteban UmerezEnviado desde mi iPadEl 21 ene 2024, a las 0:48, Otavio Cordeiro ***@***.***> escribió:﻿
Done :-)
Screenshot.2024-01-21.at.00.46.45.png (view on web)
Now it should work with Font Awesome.

**Comment by umerez** [comment]
That previous comment via email did not go very well, sorry. I was trying to thank you and attach a screenshot. 

![IMG_0206](https://github.com/otaviocc/plugin-reply-on-mastodon/assets/10687026/71704315-ebd5-4fe1-8e06-b82f808ea75d)
